it('Plays a game', () => {
    cy.visit('https://kakuna-matata.netlify.app/')
    cy.get('.createRoom > label > .inputField').type('Pikachu')
    cy.get('.createRoom > .nes-btn').click()
    cy.get('.Lobby')
    cy.get('.lobbyPlayers')
    cy.get('.PlayerCard')
    cy.get('.lobbySettings')
    cy.get('.lobbySettings > :nth-child(2)')
    cy.get('.lobbySettings > :nth-child(4)')
    cy.get('#default_select').select('1')
    cy.get(':nth-child(4) > input').dblclick().type(1).type('Cypress.io{enter}')
    // cy.get('.is-error').click()
    // cy.wait(10001)
    // cy.get('.App > :nth-child(4)')
    // cy.get('.container1')
    // cy.get('.lists')
    // cy.get('[href="/game"]').click()
  })

